pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh script: '''
                    chmod +x gradlew
                    echo "I am in build step"
                    ./gradlew build -x test
                ''',
            label: "Building Project"
            }
        }
        stage('Test')
        {
            steps {
                sh script: '''
                    echo "I am in Test step"
                    ./gradlew test
                ''',
            label: "Running Unit Test Cases"
            }
        }
        stage('Static Code Analysis')
        {
            steps {
                sh script: '''
                    echo "I am in Sonarqube scan"

                ''',
            label: "Running Sonarqube Scan"
            }
        }
        stage('Build DockerImage')
        {
            steps {
                sh script: '''
                    echo "I am Building DockerImage ="
                   docker build -t 'marsrover' -f ./.infra/docker/Dockerfile .
                   pwd
                   dir
                 ''',
            label: "Building Docker Image"

            }
        }
        stage('Publish DockerImage')
        {
            steps {
                sh script: '''
                    echo "I am Pubishing DockerImage ="
                    docker tag marsrover:latest akshit20/marsrover:latest
                    docker push akshit20/marsrover
                ''',
            label: "Publishing Docker Image"
            }
        }
}
	post{
	   always{
	     deleteDir()
	   }
	}
}
