pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh script: '''
                    chmod +x gradlew
                    echo "I am in build step"
                    ./gradlew build -x test
                ''',
            label: "Building Project"
            }
        }
        stage('Test')
        {
            steps {
                sh script: '''
                    echo "I am in Test step"
                    ./gradlew test
                ''',
            label: "Running Unit Test Cases"
            }
        }
        stage('Static Code Analysis')
        {
            steps {
                sh script: '''
                    echo "I am in Sonarqube scan"
                    ./gradlew sonarqube \
                      -Dsonar.projectKey=tavisca-akhatri_MarsRover \
                      -Dsonar.organization=tavisca-akhatri \
                      -Dsonar.host.url=https://sonarcloud.io \
                      -Dsonar.login=5b888220761ae21d5203bf2614b339b27167ccfc
                ''',
            label: "Running Sonarqube Scan"
            }
        }
        stage('Build DockerImage')
        {
            steps {
                sh script: '''
                    echo "I am Building DockerImage ="
                   docker build -t 'marsrover' -f ./.infra/docker/Dockerfile .
                 ''',
            label: "Building Docker Image"

            }
        }
        stage('Publish DockerImage')
        {
            steps {
                sh script: '''
                    echo "I am Pubishing DockerImage ="
                    docker login -u akshit20 -p Akshitkhatri12
                    docker tag marsrover:latest akshit20/myfirstrepository:latest
                    docker push akshit20/myfirstrepository
                ''',
            label: "Publishing Docker Image"
            }
        }
}
	post{
	   always{
	     deleteDir()
	   }
	}
}
